Create LICENSE
camille-le/kindle-quotations-lambda-python pull request #8
Opened 2021-09-03 23:27 UTC by camille-le

Add license to repo

2021-09-09 02:06 UTC, csdavidson requested changes

2021-09-09 02:06 UTC, csdavidson commented on LICENSE
> +Copyright (c) 2021 Camille
Camille who? 🤔

2021-09-13 01:11 UTC, camille-le commented
@csdavidson fixed - added last name

2021-09-13 06:22 UTC, csdavidson approved these changes
🚢

2021-09-26 03:50 UTC, merged